export const novelFields = [
  ['001', 'nliId'],
  ['Author', 'author'],
  ['lifetime', 'authorLifetime'],
  [' Title', 'nliTitle'],
  ['Publication Year', 'publicationYear'],
  ['Number of Pages', 'numPages'],
  ['press', 'publisher'],
  ['Genre ID unclear', 'unclearGenre'],
  ['Extracted Book Name', 'title'],
];

export const readingFields = [
  ['  ', 'title'],
  ['Name of Author', 'author'],
  ['Sex of Author', 'authorSex'],
  ['Year of Publication', 'publicationYear'],
  ['Publisher', 'publisher'],
  ['Number of Pages', 'numPages'],
  ['Sub-Genre', 'subGenre'],
  ['Division within the Novel', 'division'],
  ['Typical Chapter Length', 'typicalChapterLength'],
  ['Excerpts of Other Genres', 'excerptsOfOtherGenres'],
  ['Division to Paragraphs on a Typical Page', 'divisionToParagraphs'],
  ['Type of Narrator', 'narratorType'],
  ['Role of Narrator in the Plot', 'narratorRole'],
  ['Narrator\'s Gender, Age, Religion', 'narratorGender'],
  ['Characters in the Novel', 'characters'],
  ['Communication in the Novel', 'communication'],
  ['Number of Plot-lines', 'numPlotLines'],
  ['Novel\'s Exposition', 'exposition'],
  ['Key Events', 'keyEvents'],
  ['Fillers', 'fillers'],
  ['Other Languages Used', 'otherLanguages'],
  ['The Bodies of Texts to which the Novel Reffers', 'referrals'],
  ['Readability', 'readability'],
  ['Chronological Scope of the Novel', 'chronologicalScope'],
  ['Main Epoch(s)', 'epochs'],
  ['Main Space(s)', 'spaces'],
  ['Main Geographical Location(s)', 'locations'],
  ['Names of Places in the Novel', 'placeNames'],
  ['Centrality of Israel (State, Land)', 'centralityOfIsrael'],
  ['Themes', 'themes'],
  ['Centrality of Love', 'loveCentrality'],
  ['Type of Love', 'loveType'],
  ['Intergenerational Relationships', 'intergenerationalRelationships'],
  ['Centrality of war', 'warCentrality'],
  ['Which War', 'whichWar'],
  ['Death', 'death'],
  ['Grammatical Tense', 'grammaticalTense'],
];

